# genslides · per-machine setup: install node deps, auto-detect tools, write config/env.json, run selftest.
# Run once after cloning/installing on a new machine:  pwsh -NoProfile -File scripts/setup.ps1
$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $here

function FirstExisting([string[]]$paths) { foreach ($p in $paths) { if ($p -and (Test-Path $p)) { return $p } } return $null }
function OnPath([string]$exe) { $c = Get-Command $exe -ErrorAction SilentlyContinue; if ($c) { return $c.Source } return $null }

Write-Host "== genslides setup =="

# 1) node deps (local, self-contained)
Write-Host "installing node deps (pptxgenjs/react/react-dom/react-icons/sharp) ..."
Push-Location $root
& npm install --no-audit --no-fund 2>&1 | Select-Object -Last 3
Pop-Location
$nodeModules = Join-Path $root "node_modules"
if (-not (Test-Path (Join-Path $nodeModules "pptxgenjs"))) {
  $g = (& npm root -g 2>$null); if ($g) { $nodeModules = $g.Trim() }
}

# 2) detect tools
$soffice = FirstExisting @(
  "C:\Program Files\LibreOffice\program\soffice.exe",
  "C:\Program Files (x86)\LibreOffice\program\soffice.exe",
  (OnPath "soffice.exe"))
$chrome = FirstExisting @(
  "C:\Program Files\Google\Chrome\Application\chrome.exe",
  "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
  (OnPath "chrome.exe"))
$pdftoppm = FirstExisting @((OnPath "pdftoppm.exe"), "$env:USERPROFILE\scoop\shims\pdftoppm.exe")
$validate = FirstExisting @("$env:USERPROFILE\.claude\skills\pptx\scripts\office\validate.py", "/mnt/skills/public/pptx/scripts/office/validate.py")
$unpack   = FirstExisting @("$env:USERPROFILE\.claude\skills\pptx\scripts\office\unpack.py",   "/mnt/skills/public/pptx/scripts/office/unpack.py")

# 3) write env.json
$env = [ordered]@{
  _about          = "Auto-generated by setup.ps1 for this machine. Not committed (.gitignore)."
  nodeModules     = $nodeModules
  soffice         = $soffice
  chrome          = $chrome
  pdftoppm        = $pdftoppm
  validatePy      = $validate
  unpackPy        = $unpack
  pythonIoEncoding = "utf-8"
}
$envPath = Join-Path $root "config\env.json"
$env | ConvertTo-Json | Set-Content -Path $envPath -Encoding UTF8
Write-Host "wrote $envPath"

# 4) report missing
$missing = @()
foreach ($k in "soffice","chrome","pdftoppm","validatePy") { if (-not $env[$k]) { $missing += $k } }
if ($missing.Count) {
  Write-Host ("MISSING: " + ($missing -join ", ")) -ForegroundColor Yellow
  Write-Host "  install the tool(s) and edit config/env.json. validatePy/unpackPy come from the official 'pptx' skill." -ForegroundColor Yellow
}

# 5) selftest
Write-Host "`nrunning selftest ..."
& pwsh -NoProfile -File (Join-Path $here "selftest.ps1")
