# -*- coding: utf-8 -*-
"""
genslides · per-machine setup (cross-platform canonical; setup.ps1 is a thin wrapper).
Installs node deps, auto-detects tools, writes config/env.json, installs the
bundled QA agent definitions for Claude Code, and runs the selftest.

Usage: python scripts/setup.py [--no-selftest]
"""
import json
import os
import platform
import shutil
import subprocess
import sys

from _common import ENV_PATH, ROOT, run, utf8_stdout

WIN = platform.system() == "Windows"
MAC = platform.system() == "Darwin"
HOME = os.path.expanduser("~")


def first_existing(paths):
    for p in paths:
        if p and os.path.exists(p):
            return p
    return None


def which(*names):
    for n in names:
        p = shutil.which(n)
        if p:
            return p
    return None


def detect_soffice():
    if WIN:
        return first_existing([
            r"C:\Program Files\LibreOffice\program\soffice.exe",
            r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
            which("soffice.exe"),
        ])
    if MAC:
        return first_existing([
            "/Applications/LibreOffice.app/Contents/MacOS/soffice",
            which("soffice"),
        ])
    return which("soffice", "libreoffice")


def detect_chrome():
    if WIN:
        return first_existing([
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
            which("chrome.exe"),
        ])
    if MAC:
        return first_existing([
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "/Applications/Chromium.app/Contents/MacOS/Chromium",
            which("chrome", "chromium"),
        ])
    return which("google-chrome", "google-chrome-stable", "chromium", "chromium-browser", "chrome")


def detect_pdftoppm():
    return first_existing([
        which("pdftoppm.exe" if WIN else "pdftoppm"),
        os.path.join(HOME, "scoop", "shims", "pdftoppm.exe") if WIN else None,
    ])


def main():
    utf8_stdout()
    print("== genslides setup ==")

    # 1) node deps (local, self-contained; fall back to global if install fails)
    print("installing node deps (pptxgenjs/react/react-dom/react-icons/sharp) ...")
    npm = which("npm") or "npm"
    rc, log = run([npm, "install", "--no-audit", "--no-fund"], cwd=ROOT)
    node_modules = os.path.join(ROOT, "node_modules")
    if rc != 0 or not os.path.exists(os.path.join(node_modules, "pptxgenjs")):
        rc, g = run([npm, "root", "-g"])
        if rc == 0 and g.strip() and os.path.exists(os.path.join(g.strip(), "pptxgenjs")):
            node_modules = g.strip()
            print("local install unavailable -> using global node_modules")
        else:
            print("WARNING: pptxgenjs not found locally or globally — run npm install manually")

    # 2) detect tools
    validate = first_existing([
        os.path.join(HOME, ".claude", "skills", "pptx", "scripts", "office", "validate.py"),
        "/mnt/skills/public/pptx/scripts/office/validate.py",
    ]) or os.path.join(ROOT, "scripts", "check_pptx.py")
    unpack = first_existing([
        os.path.join(HOME, ".claude", "skills", "pptx", "scripts", "office", "unpack.py"),
        "/mnt/skills/public/pptx/scripts/office/unpack.py",
    ])
    env = {
        "_about": "Auto-generated by setup.py for this machine. Not committed (.gitignore).",
        "nodeModules": node_modules,
        "soffice": detect_soffice(),
        "chrome": detect_chrome(),
        "pdftoppm": detect_pdftoppm(),
        "validatePy": validate,
        "unpackPy": unpack,
        "pythonIoEncoding": "utf-8",
    }

    # 3) write env.json
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        json.dump(env, f, indent=2)
    print("wrote %s" % ENV_PATH)

    # 4) report missing
    missing = [k for k in ("soffice", "chrome", "pdftoppm") if not env[k]]
    if missing:
        print("MISSING: %s — install and edit config/env.json" % ", ".join(missing))
        print("  (validation needs nothing extra: bundled scripts/check_pptx.py is the fallback)")

    # 5) install bundled agent definitions for Claude Code (bare-skill installs:
    #    a skill folder's agents/ dir is NOT auto-registered; ~/.claude/agents/ is)
    agents_src = os.path.join(ROOT, "agents")
    claude_dir = os.path.join(HOME, ".claude")
    if os.path.isdir(agents_src) and os.path.isdir(claude_dir):
        dst_dir = os.path.join(claude_dir, "agents")
        os.makedirs(dst_dir, exist_ok=True)
        for f in os.listdir(agents_src):
            if f.endswith(".md"):
                shutil.copy(os.path.join(agents_src, f), os.path.join(dst_dir, f))
                print("installed agent -> ~/.claude/agents/%s" % f)

    # 6) selftest
    if "--no-selftest" not in sys.argv:
        print("\nrunning selftest ...")
        rc = subprocess.call([sys.executable, os.path.join(ROOT, "scripts", "selftest.py")])
        sys.exit(rc)


if __name__ == "__main__":
    main()
